<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homework - {{ $filterDate }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #06AC73;
            padding-bottom: 20px;
        }
        .school-name {
            font-size: 24px;
            font-weight: bold;
            color: #06AC73;
            margin-bottom: 5px;
        }
        .student-info {
            font-size: 16px;
            margin-bottom: 10px;
        }
        .print-date {
            font-size: 14px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #06AC73;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 12px;
            border-bottom: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .homework-title {
            font-weight: bold;
            color: #333;
        }
        .homework-description {
            color: #666;
            font-size: 14px;
        }
        .due-date {
            color: #e67e22;
            font-size: 12px;
            margin-top: 5px;
        }
        .teacher-info {
            font-size: 14px;
            color: #666;
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            font-size: 12px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
        @media print {
            body {
                margin: 0;
                padding: 20px;
            }
            .no-print {
                display: none;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="school-name">{{ $student->school->name ?? 'School' }}</div>
        <div class="student-info">
            Student: {{ $student->name }} | 
            Class: {{ $studentDetails->class->name ?? 'N/A' }} | 
            Section: {{ $studentDetails->section->name ?? 'N/A' }} |
            Roll No: {{ $studentDetails->roll_number ?? 'N/A' }}
        </div>
        <div class="print-title">
            <h2>Homework for {{ \Carbon\Carbon::parse($filterDate)->format('F j, Y') }}</h2>
        </div>
        <div class="print-date">Printed on: {{ $printDate }}</div>
    </div>

    @if($homeworks->count() > 0)
        <table>
            <thead>
                <tr>
                    <th style="width: 5%">#</th>
                    <th style="width: 15%">Subject</th>
                    <th style="width: 45%">Homework</th>
                    <th style="width: 20%">Teacher</th>
                    <th style="width: 15%">Due Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($homeworks as $homework)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>
                        <strong>{{ $homework->subject->name ?? 'General' }}</strong>
                    </td>
                    <td>
                        <div class="homework-title">{{ $homework->homework_title }}</div>
                        <div class="homework-description">{{ $homework->homework_description }}</div>
                        @if($homework->attachments && count($homework->attachments) > 0)
                        <div style="font-size: 12px; color: #27ae60; margin-top: 5px;">
                            📎 {{ count($homework->attachments) }} attachment(s)
                        </div>
                        @endif
                    </td>
                    <td class="teacher-info">
                        {{ $homework->teacher->name ?? 'Teacher' }}
                    </td>
                    <td>
                        @if($homework->due_date)
                            <div class="due-date">
                                {{ $homework->due_date->format('M j, Y') }}
                            </div>
                        @else
                            <div style="color: #999; font-size: 12px;">No due date</div>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div style="text-align: center; padding: 40px; color: #666;">
            <h3>No homework assigned for {{ \Carbon\Carbon::parse($filterDate)->format('F j, Y') }}</h3>
        </div>
    @endif

    <div class="footer">
        Generated by {{ $student->school->name ?? 'School' }} Student Portal
    </div>

    <script>
        window.onload = function() {
            window.print();
        }
    </script>
</body>
</html>